title : Networthify (the blog)
tagline: Awesome personal finance tools for savings extremists
author :
  name : Eric Johnson
  email : eric@networthify.com
  github : kablamo
  twitter : kablamo_
  feedburner : feedname

navigation :
  - index.html
  - categories.html
  - about.md
  
